#!/bin/bash
# Generated by Fox Optimizer - Pure Firewall Rules
# IMPORTANT: Run as root! Requires ipset package.

# 1. Setup Chain
iptables -N FOX_FILTER 2>/dev/null
iptables -F FOX_FILTER
iptables -D INPUT -j FOX_FILTER 2>/dev/null
iptables -I INPUT -j FOX_FILTER

# 3. Injecting 84 Firewall Rules
iptables -A FOX_FILTER -p icmp -s 3.3.3.3/32 --icmp-type 0 -j DROP
iptables -A FOX_FILTER -p udp -m multiport --dports 7 -j DROP
iptables -A FOX_FILTER -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 9 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 10 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 8 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 8 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 8 -j DROP
iptables -A FOX_FILTER -p icmp -s 10.0.0.0/8 --icmp-type 18 -j DROP
iptables -A FOX_FILTER -p icmp -s 192.168.0.0/16 --icmp-type 18 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 18 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 17 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 17 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 6 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 6 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 0 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 0 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 11 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 34 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 34 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 33 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 33 -j DROP
iptables -A FOX_FILTER -p icmp -s 10.0.0.0/8 --icmp-type 16 -j DROP
iptables -A FOX_FILTER -p icmp -s 192.168.0.0/16 --icmp-type 16 -j DROP
iptables -A FOX_FILTER -p icmp -s 10.0.0.0/8 --icmp-type 16 -j DROP
iptables -A FOX_FILTER -p icmp -s 192.168.0.0/16 --icmp-type 16 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 15 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 15 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 32 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 32 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 36 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 36 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 35 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 35 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 12 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 12 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 12 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 12 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 40 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 40 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 40 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 40 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 40 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 5 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 5 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 5 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 19 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 19 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 9 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 10 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 39 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 39 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 4 -j DROP
iptables -A FOX_FILTER -p icmp -s 10.0.0.0/8 --icmp-type 11 -j DROP
iptables -A FOX_FILTER -p icmp -s 192.168.0.0/16 --icmp-type 11 -j DROP
iptables -A FOX_FILTER -p icmp -s 10.0.0.0/8 --icmp-type 11 -j DROP
iptables -A FOX_FILTER -p icmp -s 192.168.0.0/16 --icmp-type 11 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 14 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 14 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 13 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 13 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 30 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 30 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 1 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 1 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 2 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 2 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 7 -j DROP
iptables -A FOX_FILTER -p icmp --icmp-type 7 -j DROP
iptables -A FOX_FILTER -p tcp --syn -j DROP
iptables -A FOX_FILTER -p tcp --syn -j DROP
iptables -A FOX_FILTER -p tcp -m multiport --dports 135,136:139 -j DROP
iptables -A FOX_FILTER -p udp -m multiport --dports 161,162 -j DROP
iptables -A FOX_FILTER -p tcp -m multiport --dports 161,162,705 -j DROP
iptables -A FOX_FILTER -p tcp -m multiport --dports 139,445 -j DROP
