#!/bin/bash
# Generated by Fox Optimizer - Pure Firewall Rules

# 1. Setup Chain
iptables -N FOX_FILTER 2>/dev/null
iptables -F FOX_FILTER
iptables -D INPUT -j FOX_FILTER 2>/dev/null
iptables -I INPUT -j FOX_FILTER

# 3. Injecting 0 Firewall Rules
