#!/bin/bash
# Generated by Fox Optimizer - Pure Firewall Rules
# IMPORTANT: Run as root! Requires ipset package.

# 1. Setup Chain
iptables -N FOX_FILTER 2>/dev/null
iptables -F FOX_FILTER
iptables -D INPUT -j FOX_FILTER 2>/dev/null
iptables -I INPUT -j FOX_FILTER

# 2. Creating 1 shared IP sets
ipset destroy fox_set0 2>/dev/null
ipset create fox_set0 hash:net
ipset add fox_set0 0.0.0.0/5
ipset add fox_set0 11.0.0.0/8
ipset add fox_set0 12.0.0.0/6
ipset add fox_set0 128.0.0.0/2
ipset add fox_set0 16.0.0.0/4
ipset add fox_set0 192.0.0.0/9
ipset add fox_set0 192.128.0.0/11
ipset add fox_set0 192.160.0.0/13
ipset add fox_set0 192.169.0.0/16
ipset add fox_set0 192.170.0.0/15
ipset add fox_set0 192.172.0.0/14
ipset add fox_set0 192.176.0.0/12
ipset add fox_set0 192.192.0.0/10
ipset add fox_set0 193.0.0.0/8
ipset add fox_set0 194.0.0.0/7
ipset add fox_set0 196.0.0.0/6
ipset add fox_set0 200.0.0.0/5
ipset add fox_set0 208.0.0.0/4
ipset add fox_set0 224.0.0.0/3
ipset add fox_set0 32.0.0.0/3
ipset add fox_set0 64.0.0.0/2
ipset add fox_set0 8.0.0.0/7

# 3. Injecting 85 Firewall Rules
iptables -A FOX_FILTER -p icmp -s 3.3.3.3/32 --icmp-type 0 -j DROP
iptables -A FOX_FILTER -p udp -m multiport --dports 7 -j DROP
iptables -A FOX_FILTER -m set --match-set fox_set0 src -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 9 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 10 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 8 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 8 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 8 -j DROP
iptables -A FOX_FILTER -p icmp -s 10.0.0.0/8 --icmp-type 18 -j DROP
iptables -A FOX_FILTER -p icmp -s 192.168.0.0/16 --icmp-type 18 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 18 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 17 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 17 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 6 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 6 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 3 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 0 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 0 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 11 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 34 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 34 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 33 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 33 -j DROP
iptables -A FOX_FILTER -p icmp -s 10.0.0.0/8 --icmp-type 16 -j DROP
iptables -A FOX_FILTER -p icmp -s 192.168.0.0/16 --icmp-type 16 -j DROP
iptables -A FOX_FILTER -p icmp -s 10.0.0.0/8 --icmp-type 16 -j DROP
iptables -A FOX_FILTER -p icmp -s 192.168.0.0/16 --icmp-type 16 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 15 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 15 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 32 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 32 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 36 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 36 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 35 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 35 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 12 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 12 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 12 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 12 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 40 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 40 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 40 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 40 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 40 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 5 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 5 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 5 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 19 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 19 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 9 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 10 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 39 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 39 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 4 -j DROP
iptables -A FOX_FILTER -p icmp -s 10.0.0.0/8 --icmp-type 11 -j DROP
iptables -A FOX_FILTER -p icmp -s 192.168.0.0/16 --icmp-type 11 -j DROP
iptables -A FOX_FILTER -p icmp -s 10.0.0.0/8 --icmp-type 11 -j DROP
iptables -A FOX_FILTER -p icmp -s 192.168.0.0/16 --icmp-type 11 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 14 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 14 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 13 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 13 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 30 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 30 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 1 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 1 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 2 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 2 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 7 -j DROP
iptables -A FOX_FILTER -p icmp -m set --match-set fox_set0 src --icmp-type 7 -j DROP
iptables -A FOX_FILTER -p tcp -m set --match-set fox_set0 src --syn -j DROP
iptables -A FOX_FILTER -p tcp -m set --match-set fox_set0 src --syn -j DROP
iptables -A FOX_FILTER -p tcp -m set --match-set fox_set0 src -m multiport --dports 135,136:139 -j DROP
iptables -A FOX_FILTER -p udp -m multiport --dports 161,162 -j DROP
iptables -A FOX_FILTER -p udp -m set --match-set fox_set0 src -m multiport --dports 161,162 -j DROP
iptables -A FOX_FILTER -p tcp -m set --match-set fox_set0 src -m multiport --dports 161,162,705 -j DROP
iptables -A FOX_FILTER -p tcp -m set --match-set fox_set0 src -m multiport --dports 139,445 -j DROP
